export const piyuuuQuotes = {
  loading: [
    "Brushing up on some knowledge for you... 🪥",
    "Your tooth fairy is working overtime! 🧚",
    "Studying hard or hardly studying? Let's find out! 😄",
    "Piyuuu's brain cells are charging! ⚡",
    "Fetching some pearly white wisdom... 🦷",
    "Loading knowledge straight to your brain! 🧠",
    "This is going to be so good, wait for it... ✨",
    "The dental gods are preparing your content! 🙏",
    "Mixing up a batch of flashcards... 🧪",
    "Piyuuu mode: ACTIVATED 💪",
    "Your future dentist self is thanking you! 🩺",
    "Almost there... don't lose your patience! 😊",
    "Generating peak academic content! 📚",
    "The AI is feeling extra smart today! 🤖",
    "Making something special for our favorite student! 💖",
    "Loading... like a dental implant osseointegrating! 🦴",
    "Plot twist: the AI is also studying for exams! 📝",
    "This content is handpicked by the tooth fairy! 🧚‍♀️",
  ],

  completion: [
    "You're one step closer to Dr. Piyuuu! 🩺",
    "That was smooth, like a fresh dental polish! ✨",
    "Ka-ching! Knowledge deposited! 💰",
    "Your brain just got a cavity-free checkup! 🦷",
    "10/10 dentist would recommend this study session! ⭐",
    "Piyuuu's IQ just went up by 0.001! 📈",
    "You're basically a dental encyclopedia now! 📖",
    "That's the spirit! Keep grinding (not your teeth)! 😬",
    "Nailed it! Like a dental crown! 👑",
    "Your knowledge is now shinier than a polished tooth! ✨",
    "Another topic conquered by the great Piyuuu! 🏆",
    "If studying was a sport, you'd be Olympic level! 🥇",
    "Your future patients are in good hands! 🤲",
    "That's some premium-grade knowledge right there! 💎",
    "You're making your tooth fairy proud! 🧚",
  ],

  encouragement: [
    "You've got this, Piyuuu! 💪",
    "Every flashcard makes you a better dentist! 🦷",
    "Small steps, big dreams! 🌟",
    "The only way is up, Piyuuu! 🚀",
    "You're doing amazing, sweetie! 💖",
    "Believe in yourself like I believe in you! 🦷",
    "Hard work pays off, and you're working SO hard! 💪",
    "Future Dr. Piyuuu in the making! 🩺",
    "You're not just studying, you're building a future! 🔮",
    "I'm just a tooth app, but I'm SO proud of you! 🥹",
    "Piyuuu = Potential + Intelligence + Yesss! ✨",
    "Keep going, you're doing great! 🌈",
    "Today's effort = tomorrow's success! 📈",
    "You make studying look easy! 😎",
    "The dental world is lucky to have you! 🌍",
  ],

  dentalFacts: [
    "Fun fact: Your mouth produces enough saliva in a lifetime to fill two swimming pools! 🏊",
    "Did you know? A snail has about 25,000 teeth! That's a lot of dental work! 🐌",
    "Tooth enamel is the hardest substance in the human body! Stronger than bone! 💪",
    "The average person spends only 48 seconds brushing their teeth. Aim for 2 minutes! ⏱️",
    "Blue toothbrushes are used more than red ones worldwide! 🔵",
    "A tooth that's been knocked out can survive 15 minutes outside the mouth! ⏰",
    "People who drink 3+ glasses of soda daily have 62% more tooth decay! 🥤",
    "Ancient Egyptians used eggshells and ground up ox hooves as toothpaste! 🥚",
    "The first toothbrush was a chewed stick from the Neem tree! 🌳",
    "Your tongue print is as unique as your fingerprint! 👅",
    "Teeth are the only part of the body that can't repair themselves! Take care! 🦷",
    "The average child has 20 teeth, adults have 32, and wisdom teeth make 28-32! 👶",
    "A donkey's teeth are longer than its skull! But don't worry, you won't need that info! 🫏",
    "Tooth decay is the second most common disease after the common cold! 🤧",
  ],

  lateNight: [
    "Burning the midnight oil, Piyuuu? Your dedication is amazing! 🌙",
    "It's late! Don't forget to brush before bed! 😴",
    "The owl approves of your late-night study session! 🦉",
    "Even the moon is impressed by your hard work! 🌕",
    "Remember: sleep helps memory consolidation! Take breaks! 💤",
    "Late night studying hits different. You've got this! ✨",
    "The stars are rooting for you, Piyuuu! ⭐",
    "Your future self will thank you for this! Now go to sleep eventually! 😊",
  ],

  earlyMorning: [
    "Early bird gets the... dental knowledge! 🐦",
    "Good morning, future Dr. Piyuuu! ☀️",
    "Rise and shine, it's study time! 🌅",
    "You're up earlier than a dental appointment! 😄",
    "Morning brain = fresh brain. Let's learn! 🧠",
    "The sun is jealous of your early morning glow! 🌞",
  ],

  random: [
    "You know what's cool? YOU, for studying dentistry! 😎",
    "If teeth could talk, they'd say 'thank you' for learning about them! 🦷",
    "Plot twist: you're actually a genius and don't know it yet! 🧠",
    "Somewhere, a tooth is smiling because of you! 😊",
    "You're like a superhero, but for teeth! 🦸‍♀️",
    "Fun fact: you're the best thing that happened to this app! 💖",
    "I'm just a bunch of code, but I believe in you! 🤖💕",
    "Piyuuu sounds like 'piu piu' which is what knowledge does to your brain! Pew pew! 🔫✨",
    "You're making the tooth fairy's job easier! 🧚",
    "If studying was easy, everyone would be a dentist. But YOU'RE doing it! 💪",
  ],
};

export const secretMessages = [
  "You found a secret! 🎉",
  "Piyuuu's secret stash of wisdom! 📦",
  "Hidden like a root canal... but happier! 🦷",
  "You're a treasure hunter of knowledge! 🗺️",
  "Easter egg found! You get: virtual hug! 🤗",
  "The tooth fairy left this just for you! 🧚",
  "Secret unlocked! +10 coolness points! 😎",
  "You're officially a Piyuuu power user! ⚡",
];

export const studyStreakMessages = {
  1: "First step of many! You've got this! 🌱",
  3: "Three in a row! You're on fire! 🔥",
  5: "FIVE topics! You're unstoppable! 🚀",
  7: "A whole week of learning! You're legendary! 👑",
  10: "TEN topics?! You're basically a dental professor! 🎓",
  15: "FIFTEEN?! Piyuuu, you're a machine! 🤖",
  20: "We're not worthy! We're not worthy! 🙇",
  50: "Are you even real?! You're incredible! 🦄",
  100: "HUNDRED?! Okay, you need to take a break! 😂",
};
